import React, { Component } from 'react'

const options = 
[ 
    `Art of Peace`,
    "Aikido",
    "Aiki",
    "adversary",
    "agression",
    'anger', 
    `art`,
    "atemi",
    'attack',
    "battle",
    "beginner", 
    "Beginner's Mind",
    'belt',
    'blend',
    "body", 
    "bow", 
    "budo",
    "bravery",
    "breath",
    "center",
    'challenge',
    "challenger",
    'compassion',
    'competition', 
    'control',   
    'cosmos',
    'darkness',
    'death',
    'decay',
    'defeat',
    'desire',
    'destroy',
    "divine",
    'devoted',
    "economy",
    "empty",
    "enemies",
    "energy",
    "enlightened",
    'evil',
    "fail",
    "failure",
    "faith",
    "fear",
    "fire and water",
    `foe`,
    'force',
    "forging",
    "foundation",
    "free",
    "friendship",
    "God", 
    `gods`,
    'growth',
    "hardship",
    "harmony",
    "heart",
    "Heaven",
    "Heaven and Earth",
    'human', 
    `iron`,
    "injure",
    'joy',
    'kami',
    "love",
    'life',
    'life source',
    "light",
    "light and heat",
    "mankind",
    "martial arts",
    "master",
    'medicine',
    "mind",
    'mission',
    "mistake",
    "money",
    "movemonet",
    'mountain',
    "Mount Fuji",
    "nature",
    "non-resistance",
    "nonviolence",
    "opponent",
    "pain",
    "path",
    'paths',
    'pacify',
    'peace',
    "pleasure",
    "polish",
    'possessed',
    "potential",
    "power",
    "powerful",
    'Power of Love',
    'prayer', 
    "practice",
    "purpose",
    'redirect',
    "religion",
    "Samurai",
    'seclude',
    'self',
    'self-sacrifice',
    "senses", 
    "shield",
    "Shihonage",
    'sky',
    "slack",
    "society",
    'soul',
    'source',
    'Source of life',
    'spirit',
    "strategy",
    "strength",
    "strong",
    "study",
    'stillness',
    "substance",
    'success', 
    'suffer',
    'sword',
    "True Budo",
    "True Victory",
    "true",
    "truth",
    "teachings",
    "technique",
    "throw",
    "train",
    'trees',
    "universe",
    'warmth',
    "war",
    'warrior',
    'water',
    "wave",
    "way",
    'Way of the Warrior', 
    "weapon",
    'wise',
    'wisdom',
    "world",
    'valley',
    "victory", 
    "voice",
    "void"
  ]

  export default options 